In [5]:
import pandas as pd
import numpy as np
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [6]:
data = pd.read_csv("scraped.csv", encoding='latin-1')
data.head(3)

,openalex_id,title,doi,abstract,publish_time,authors,journal,pmcid,pubmed_id
0,https://openalex.org/W2110829397,PROBLEMS OF SPACE BIOLOGY,NaN,Space biology - effect of radiation exposure a...,1963-03-25,N. M. Sisakyan,Defense Technical Information Center (DTIC),NaN,NaN
1,https://openalex.org/W2035753075,Chemical space and biology,https://doi.org/10.1038/nature03192,Chemical space--which encompasses all possible...,2004-12-15,Christopher M. Dobson,Nature,NaN,https://pubmed.ncbi.nlm.nih.gov/15602547
2,https://openalex.org/W2988387100,Space biology and medicine.,NaN,Perhaps one of the greatest gifts that has bee...,1979-10-01,Arnauld Nicogossian; Stanley R. Mohler; Ð. Ð...,PubMed,NaN,https://pubmed.ncbi.nlm.nih.gov/11902165

In [7]:
df_csv = data
df_csv = df_csv[['openalex_id','title','doi','abstract','publish_time','authors','journal','doi','pmcid','pubmed_id']]
df_csv.head()

,openalex_id,title,doi,abstract,publish_time,authors,journal,doi,pmcid,pubmed_id
0,https://openalex.org/W2110829397,PROBLEMS OF SPACE BIOLOGY,NaN,Space biology - effect of radiation exposure a...,1963-03-25,N. M. Sisakyan,Defense Technical Information Center (DTIC),NaN,NaN,NaN
1,https://openalex.org/W2035753075,Chemical space and biology,https://doi.org/10.1038/nature03192,Chemical space--which encompasses all possible...,2004-12-15,Christopher M. Dobson,Nature,https://doi.org/10.1038/nature03192,NaN,https://pubmed.ncbi.nlm.nih.gov/15602547
2,https://openalex.org/W2988387100,Space biology and medicine.,NaN,Perhaps one of the greatest gifts that has bee...,1979-10-01,Arnauld Nicogossian; Stanley R. Mohler; Ð. Ð...,PubMed,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/11902165
3,https://openalex.org/W3114753755,Advantages and Limitations of Current Microgra...,https://doi.org/10.3390/app11010068,Human Space exploration has created new challe...,2020-12-23,Francesca Ferranti; Marta Del Bianco; Claudia ...,Applied Sciences,https://doi.org/10.3390/app11010068,NaN,NaN
4,https://openalex.org/W371744478,AN UPDATE ON PLANT SPACE BIOLOGY,NaN,Space craft in low-Earth orbit can provide a m...,2011-08-30,Chris Wolverton; John Z. Kiss,Digital Commons - OWU (Ohio Wesleyan University),NaN,NaN,NaN

In [8]:
print(len(df_csv))
df_csv = df_csv[~df_csv['abstract'].isnull()]
print(len(df_csv))

199993
199989

In [9]:
df_csv['abstract'] = df_csv['abstract'].apply(lambda x:
                                          x.replace('BACKGROUND:','').replace('BACKGROUNDS:','').replace('OBJECTIVES:','')
                                          .replace('OBJECTIVE:','').replace('METHODS:','').replace('METHOD:','')
                                          .replace('RESULTS:','').replace('RESULT:','')
                                          .replace('CONCLUSION:','').replace('CONCLUSIONS:',''))

In [10]:
df_csv['abstract'] = df_csv['abstract'].apply(lambda x: x.lower())
df_csv['abstract'] = df_csv['abstract'].apply(lambda x: x.replace('this article is protected by copyright. all rights reserved',''))

In [11]:
df_csv.to_csv('abstract_final.csv', index=None)

In [12]:
print(len(df_csv))
df_csv = df_csv[~df_csv['publish_time'].isnull()]
print(len(df_csv))

199989
199921

In [13]:
df = df_csv
df['publish_time_new'] = pd.to_datetime(df['publish_time'], format='%Y-%m-%d',errors='coerce')

In [14]:
print(len(df))
df = df[df.publish_time_new != "NaT"]
print(len(df))

199921
199921

In [ ]:
#OPTIONAL
import datetime
df= df[df['publish_time_new']>'2020-01-01']
len(df)

18864

In [15]:
# IF NOT USED: USE LANGUAGE = MULTILINGUAL IN TRAINING THE MODEL
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0
def langdet (x):
    try:
        return detect(x)
    except:
        return "NA"
df['lang'] = df['abstract'].apply(lambda x: langdet(x))
df = df[df['lang'].str.contains('en')]
df.to_csv('articles_clean_text_eng.csv', index=None)
len(df)

199102

In [100]:
import pandas as pd
df = pd.read_csv('articles_clean_text_eng.csv')

In [ ]:
df1 = df
len(df1) # MUST BE SAME AS THE PREVIOUS STEP

99640

In [130]:
unk = """'Unknown'
'Not Known'
'Little is known'
'Unrevealed'
'Uncertain'
'Undetermined'
'Understudied'
'Unexplored'
'Unclear'
'Not fully understood'
'Literature gap'
'Research gap'
'Knowledge gap'
'Future studies'
'Future research'
'Research problem'
'More studies'
'More research'
'Further studies'
'Further research'"""
unk = unk.replace("\n",",").replace("'","").lower().split(",")
unk= "|".join(unk)
unk

'unknown|not known|little is known|unrevealed|uncertain|undetermined|understudied|unexplored|unclear|not fully understood|literature gap|research gap|knowledge gap|future studies|future research|research problem|more studies|more research|further studies|further research'

In [131]:
df2 = df1[df1.abstract.str.contains(unk)]
len(df2)

12816

In [4]:
# Commented lines allow for local stopword database.
import re
import nltk
import string
from textblob import TextBlob
# nltk.download('stopwords')
# nltk.download('wordnet')
stopword = nltk.corpus.stopwords.words('english')
#my_file = open("stopwords.txt", "r")
#content = my_file.read().split('\n')
#stopword.extend(content)
stopword = list(set(stopword))
stopword = [w.strip() for w in stopword]
stopword = set(stopword)
wn = nltk.WordNetLemmatizer()
ps = nltk.PorterStemmer()
from nltk import bigrams, trigrams

def removeWeirdChars(text):
    weirdPatterns = re.compile("["u"\U0001F600-\U0001F64F"u"\U0001F300-\U0001F5FF"u"\U0001F680-\U0001F6FF"u"\U0001F1E0-\U0001F1FF"u"\U00002702-\U000027B0"u"\U000024C2-\U0001F251"u"\U0001f926-\U0001f937"u'\U00010000-\U0010ffff'
                               u"\u200d"u"\u2640-\u2642"u"\u2600-\u2B55"u"\u23cf"u"\u23e9"u"\u231a"u"\u3030"u"\ufe0f"u"\u2069"u"\u2066"u"\u200c"u"\u2068"u"\u2067""]+", flags=re.UNICODE)
    return weirdPatterns.sub(r'', text)
def remove_punct(text):
    text  = "".join([char for char in text if char not in string.punctuation])
    text = re.sub('[0-9]+', '', text)
    return text
def tokenization(text):
    text = text.split()#re.split('\W+', text)
    text = ','.join(set(text))
    return text
def remove_stopwords(text):
    text = [word.strip() for word in text.split() if word not in stopword]
    text = ' '.join(text)
    return text
def stemming(text): # This is unused
    text = [ps.stem(word) for word in text.split()]
    text = ' '.join(text)
    return text

def lemmatizer(text): # This is unused
    text = [wn.lemmatize(word) for word in text.split()]
    text = ' '.join(text)
    return text
def clean_text(text):
    text_lc = " ".join([word.lower() for word in text.split() if word not in string.punctuation]) # remove puntuation
    text_rc = re.sub('[0-9]+', '', text_lc)
    tokens = re.split('\W+', text_rc)    # tokenization
    text = [word for word in tokens if word not in stopword]  # remove stopwords and stemming
    text = ' '.join(text)
    return text


df2['clean_text'] = df2['abstract'].apply(lambda x: clean_text(x))

NameError: name 'df2' is not defined

In [3]:
from nltk.tokenize import sent_tokenize
nltk.download('punkt_tab')

wl = unk.split("|")
def sentence(x):
    s, w = [], []
    sent = sent_tokenize(x)
    if len(sent)<=1:
        s, w =["-1"], ["-1"]
    else:
        for c, i in enumerate(sent):
            for j in wl:
                if j in i:
                    w.append(j)
                    if c==0 or c==len(sent)-1:
                        s.append(i)
                    else:
                        s.append(sent[c-1])
                        s.append(sent[c])
                        s.append(sent[c+1])
    s = list(dict.fromkeys(s))
    w = list(dict.fromkeys(w))
    C = ".".join(s)
    D = ",".join(w)
    return pd.Series([C, D])

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\shaur\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

NameError: name 'unk' is not defined

In [140]:
df2[['sentences', 'words']] = df2['abstract'].apply(sentence)

In [141]:
df2.head()

,openalex_id,title,doi,abstract,publish_time,authors,journal,doi.1,pmcid,pubmed_id,publish_time_new,lang,clean_text,sentences,words
6,https://openalex.org/W2160719116,Synthetic biology for the directed evolution o...,https://doi.org/10.1039/c4cs00351a,the amino acid sequence of a protein affects b...,2014-12-15,Andrew Currin; Neil Swainston; Philip J. Day; ...,Chemical Society Reviews,https://doi.org/10.1039/c4cs00351a,NaN,https://pubmed.ncbi.nlm.nih.gov/25503938,2014-12-15,en,amino acid sequence protein affects structure ...,enzymologists distinguish binding (kd) and cat...,unknown
8,https://openalex.org/W3016143870,Space Radiation Biology for âLiving in Spaceâ,https://doi.org/10.1155/2020/4703286,space travel has advanced significantly over t...,2020-01-01,Satoshi Furukawa; Aiko Nagamatsu; Mitsuru Neno...,BioMed Research International,https://doi.org/10.1155/2020/4703286,NaN,https://pubmed.ncbi.nlm.nih.gov/32337251,2020-01-01,en,space travel advanced significantly last six d...,future research that furthers our understandin...,future research
26,https://openalex.org/W1424654272,Planning Algorithms,https://doi.org/10.1017/cbo9780511546877,planning algorithms are impacting technical di...,2006-05-29,Steven M. LaValle,Cambridge University Press eBooks,https://doi.org/10.1017/cbo9780511546877,NaN,NaN,2006-05-29,en,planning algorithms impacting technical discip...,the treatment is centered on robot motion plan...,uncertain
28,https://openalex.org/W4366735078,Perspectives for plant biology in space and an...,https://doi.org/10.1038/s41526-023-00315-x,advancements in plant space biology are requir...,2023-08-21,Veronica De Micco; Giovanna Aronne; Nicol Capl...,npj Microgravity,https://doi.org/10.1038/s41526-023-00315-x,NaN,https://pubmed.ncbi.nlm.nih.gov/37604914,2023-08-21,en,advancements plant space biology required real...,this apparent paradox is a current research ch...,knowledge gap
58,https://openalex.org/W2056901756,Plant biology in space: recent accomplishments...,https://doi.org/10.1111/plb.12127,gravity has shaped the evolution of life since...,2013-12-23,GÃ¼nter Ruyters; Markus Braun,Plant Biology,https://doi.org/10.1111/plb.12127,NaN,https://pubmed.ncbi.nlm.nih.gov/24373009,2013-12-23,en,gravity shaped evolution life since origin how...,a chapter summarising major scientific breakth...,future research

In [142]:
len(df2),len(df2.pubmed_id==None)

(12816, 12816)

In [143]:
df2.to_csv("articles_with_sentences and words1.csv", index=None)

# Data

In [144]:
import pandas as pd
df2 = pd.read_csv('articles_with_sentences and words1.csv')

In [145]:
df2.head(2)

,openalex_id,title,doi,abstract,publish_time,authors,journal,doi.1,pmcid,pubmed_id,publish_time_new,lang,clean_text,sentences,words
0,https://openalex.org/W2160719116,Synthetic biology for the directed evolution o...,https://doi.org/10.1039/c4cs00351a,the amino acid sequence of a protein affects b...,2014-12-15,Andrew Currin; Neil Swainston; Philip J. Day; ...,Chemical Society Reviews,https://doi.org/10.1039/c4cs00351a,NaN,https://pubmed.ncbi.nlm.nih.gov/25503938,2014-12-15,en,amino acid sequence protein affects structure ...,enzymologists distinguish binding (kd) and cat...,unknown
1,https://openalex.org/W3016143870,Space Radiation Biology for âLiving in Spaceâ,https://doi.org/10.1155/2020/4703286,space travel has advanced significantly over t...,2020-01-01,Satoshi Furukawa; Aiko Nagamatsu; Mitsuru Neno...,BioMed Research International,https://doi.org/10.1155/2020/4703286,NaN,https://pubmed.ncbi.nlm.nih.gov/32337251,2020-01-01,en,space travel advanced significantly last six d...,future research that furthers our understandin...,future research

In [146]:
print(len(df2))


# Drop duplicates only on non-null values

print(len(df2))
df2 = df2.drop_duplicates(subset=['openalex_id'], keep='first')
print(f"After deduplicating on openalex_id: {len(df2)}")

cols_to_dedup = ['doi', 'pmcid', 'pubmed_id']

for col in cols_to_dedup:
    df_with_val = df2[df2[col].notna()].drop_duplicates(subset=[col], keep='first')
    df_without_val = df2[df2[col].isna()]
    df2 = pd.concat([df_with_val, df_without_val]).reset_index(drop=True)
    print(f"After deduplicating on {col}: {len(df2)}")

12816
12816
After deduplicating on openalex_id: 12815
After deduplicating on doi: 12803
After deduplicating on pmcid: 12803
After deduplicating on pubmed_id: 12803

In [147]:
#docs = df2[df2['clean_text'].notna()].clean_text.to_list() 
# OR IF OVER 70,000 or so are left: 
docs = df2[df2['sentences'].notna()].clean_text.to_list()

In [148]:
docs[2]

print(len(docs))

12803

# **Topic Modeling**

In [ ]:
from bertopic import BERTopic


# Inject it into your BERTopic initialization
topic_model = BERTopic(
    language="english", # OR language="multilingual"
    calculate_probabilities=True, 
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

2026-05-26 21:22:47,967 - BERTopic - Embedding - Transforming documents to embeddings.

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 25237.37it/s]
Batches: 100%|██████████| 401/401 [02:04<00:00,  3.23it/s]
2026-05-26 21:24:54,497 - BERTopic - Embedding - Completed ✓
2026-05-26 21:24:54,499 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-26 21:24:55,400 - BERTopic - Dimensionality - Completed ✓
2026-05-26 21:24:55,401 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-26 21:25:05,013 - BERTopic - Cluster - Completed ✓
2026-05-26 21:25:05,016 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-26 21:25:06,120 - BERTopic - Representation - Completed ✓

## Extracting Topics

In [ ]:
freq = topic_model.get_topic_info(); freq.head(15) # -1 should be igonored (filler words)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,4563,-1_google_scholar_pubmed_species,"[google, scholar, pubmed, species, data, scopu...",[cells building blocks tissues organs organism...
1,0,197,0_cancer_tumor_angiomyolipoma_cells,"[cancer, tumor, angiomyolipoma, cells, melanom...",[despite recent notable progress medical scien...
2,1,176,1_walls_wall_aba_auxin,"[walls, wall, aba, auxin, arabidopsis, cell, p...",[grand challenge coming decades feed rapidly g...
3,2,151,2_microbial_water_microorganisms_bacteria,"[microbial, water, microorganisms, bacteria, s...",[past years since inception microbial biotechn...
4,3,142,3_health_women_risk_covid,"[health, women, risk, covid, mortality, age, d...",[widely thought lifespans increasing globally ...
5,4,133,4_students_education_learning_student,"[students, education, learning, student, gende...",[covid pandemic impacted education levels vari...
6,5,132,5_mitochondrial_mitochondria_membrane_import,"[mitochondrial, mitochondria, membrane, import...",[small tim proteins mitochondrial intermembran...
7,6,116,6_bioh_protein_structural_mass,"[bioh, protein, structural, mass, proteins, pr...",[describe use antibody based proteomics involv...
8,7,113,7_lung_sp_dcs_iai,"[lung, sp, dcs, iai, ifn, il, mice, pulmonary,...",[research molecular markers functions dendriti...
9,8,110,8_brain_astrocytes_cns_hiv,"[brain, astrocytes, cns, hiv, oatp, microglia,...",[past decades central nervous system cns perip...
10,9,104,9_fish_fisheries_fishing_reef,"[fish, fisheries, fishing, reef, management, f...",[abstract coral reef fisheries great importanc...
11,10,100,10_parameter_parameters_model_estimation,"[parameter, parameters, model, estimation, mod...",[ordinary differential equation ode models oft...
12,11,95,11_stations_science_field_conservation,"[stations, science, field, conservation, commi...",[ensure responsible application ecological kno...
13,12,83,12_species_models_distribution_spatial,"[species, models, distribution, spatial, sdms,...",[maps species distributions habitat suitabilit...
14,13,83,13_microgravity_spaceflight_space_astronauts,"[microgravity, spaceflight, space, astronauts,...",[apollo astronauts first set foot surface moon...

In [118]:
len(freq)

179

In [119]:
topic_model.get_topic(0)  # Select the most frequent topic

[('cancer', np.float64(0.032321445792297676)),
 ('tumor', np.float64(0.026813975536218695)),
 ('angiomyolipoma', np.float64(0.012145602321261325)),
 ('cells', np.float64(0.011725575964960282)),
 ('melanoma', np.float64(0.011204970168283262)),
 ('breast', np.float64(0.010616707433602308)),
 ('tumors', np.float64(0.0102794730626623)),
 ('renal', np.float64(0.009802828908462872)),
 ('metastasis', np.float64(0.00977074023632018)),
 ('flt', np.float64(0.00921903745166727))]

## Visualize Topics

NOTE CONSIDER: (https://github.com/cpsievert/LDAvis):

In [123]:
fig = topic_model.visualize_topics()
topic_model.visualize_topics()
fig.write_html(
    "topics_visualization.html",
    config={'responsive': True, 'displayModeBar': True}
)

In [122]:
fig_2 =topic_model.visualize_hierarchy(top_n_topics=100)
topic_model.visualize_hierarchy(top_n_topics=100)
fig_2.write_html("topics_hierarchy.html")

## Visualize Terms

In [124]:
topic_model.visualize_barchart(top_n_topics=10)

In [125]:
topic_model.visualize_term_rank()

# **Topic Representation**
After having created the topic model, you might not be satisfied with some of the parameters you have chosen. Fortunately, BERTopic allows you to update the topics after they have been created.

This allows for fine-tuning the model to your specifications and wishes.

## Update Topics
When you have trained a model and viewed the topics and the words that represent them,
you might not be satisfied with the representation. Perhaps you forgot to remove
stopwords or you want to try out a different `n_gram_range`. We can use the function `update_topics` to update
the topic representation with new parameters for `c-TF-IDF`:

## Topic Reduction
We can also reduce the number of topics after having trained a BERTopic model. The advantage of doing so,
is that you can decide the number of topics after knowing how many are actually created. It is difficult to
predict before training your model how many topics that are in your documents and how many will be extracted.
Instead, we can decide afterwards how many topics seems realistic:

In [ ]:
new_topics, new_probs = topic_model.reduce_topics(docs, topics, probs, nr_topics=50)

TypeError: BERTopic.reduce_topics() got multiple values for argument 'nr_topics'

In [ ]:
freq = topic_model.get_topic_info(); freq.head(15)

    Topic  Count                                       Name
0      -1   7581                           -1_the_and_of_to
1       0    256        0_syndrome_respiratory_acute_severe
2       1    248          1_telehealth_telemedicine_care_to
3       2    224           2_thrombosis_patients_venous_vte
4       3    218        3_pregnancy_pregnant_women_neonates
5       4    216  4_cardiac_myocarditis_myocardial_patients
6       5    177         5_neurological_gbs_brain_cognitive
7       6    158       6_surgery_surgical_elective_pandemic
8       7    149    7_ecmo_ventilation_patients_respiratory
9       8    146              8_model_the_parameters_models
10      9    144     9_antibodies_bnt162b2_vaccine_antibody
11     10    138              10_mental_health_pandemic_the
12     11    136      11_learning_online_students_education
13     12    136            12_nurses_health_workers_mental
14     13    124  13_vaccine_vaccination_hesitancy_vaccines

In [ ]:
topic_model.visualize_topics()

In [11]:
topic_model.visualize_barchart(top_n_topics=20)

In [12]:
topic_model.visualize_hierarchy(top_n_topics=50)

In [ ]:
len(new_topics),len(topics)

(12853, 12853)

In [ ]:
df2["topics"] = topics
df2["new_topics"] = new_topics

In [ ]:
!ls

'articles_with_sentences and words1.csv'   drive   sample_data

In [ ]:
df2.to_csv("articles_with_topics.csv",index=None)

# Analysis

In [ ]:
import pandas as pd
df2 = pd.read_csv("articles_with_topics.csv")

In [ ]:
df2.columns

Index(['cord_uid', 'title', 'doi', 'abstract', 'publish_time', 'authors',
       'journal', 'doi.1', 'pmcid', 'pubmed_id', 'publish_time_new', 'lang',
       'sentences', 'words', 'topics', 'new_topics'],
      dtype='object')

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def ubt(x):
    word_data = x
    #word_data = "lime soda is the best selling item in fast food stores"

    # load nltk's stop word list
    stop_words = list(stopwords.words('english'))
    # extend the stop words list
    #stop_words.extend(["best", "selling", "item", "fast"])

    # tokenise the string and remove stop words
    word_tokens = word_tokenize(word_data)
    clean_word_data = [w for w in word_tokens if not w.lower() in stop_words]

    # get bigrams
    bigrams_list = [" ".join(item) for item in nltk.bigrams(clean_word_data)]
    #print(bigrams_list)

    # get trigrams
    trigrams_list = [" ".join(item) for item in nltk.trigrams(clean_word_data)]
    #print(trigrams_list)
    lst = []
    lst.extend(clean_word_data)
    lst.extend(bigrams_list)
    lst.extend(trigrams_list)
    from collections import Counter
    cnt = Counter(lst)
    del cnt["."]
    return cnt.most_common(50)

In [ ]:
import re
dst =""
for i in range(191):
    st = " ".join(df2[df2.topics==i]["sentences"].tolist())
    st = re.sub(r'[^a-zA-Z0-9. ]', '', st)
    dst+="topic-"+str(i)
    dst +="\n"
    dst += str(ubt(st))
    dst +="\n"

In [ ]:
import re
dst1 =""
for i in range(50):
    st = " ".join(df2[df2.new_topics==i]["sentences"].tolist())
    st = re.sub(r'[^a-zA-Z0-9. ]', '', st)
    dst1+="topic-"+str(i)
    dst1 +="\n"
    dst1 += str(ubt(st))
    dst1 +="\n"

In [ ]:
dst += "\n\n\n *********************Reduced Topics*********************\n\n\n"
dst +=dst1
print(dst)

topic-0
[('telehealth', 184), ('care', 181), ('telemedicine', 148), ('patients', 147), ('pandemic', 135), ('covid19', 121), ('research', 117), ('use', 94), ('future', 90), ('covid19 pandemic', 83), ('health', 79), ('services', 67), ('patient', 67), ('access', 55), ('needed', 54), ('studies', 52), ('known', 46), ('however', 45), ('future research', 45), ('little', 44), ('little known', 43), ('study', 42), ('unknown', 40), ('may', 40), ('satisfaction', 40), ('inperson', 37), ('. future', 37), ('. however', 34), ('among', 33), ('using', 32), ('healthcare', 32), ('. research', 32), ('technology', 31), ('clinical', 30), ('visits', 30), ('impact', 29), ('pandemic .', 29), ('delivery', 28), ('outcomes', 28), ('health care', 28), ('care .', 28), ('medical', 25), ('barriers', 25), ('implementation', 25), ('practice', 25), ('interventions', 24), ('improve', 23), ('review', 22), ('research needed', 22), ('pediatric', 21)]
topic-1
[('covid19', 301), ('patients', 231), ('risk', 90), ('unknown', 85), ('studies', 80), ('vte', 61), ('thrombosis', 60), ('covid19 patients', 58), ('disease', 57), ('venous', 56), ('pulmonary', 52), ('anticoagulation', 52), ('covid19 .', 47), ('thromboembolism', 45), ('thrombotic', 45), ('unknown .', 45), ('associated', 44), ('however', 44), ('pe', 43), ('patients covid19', 42), ('research', 41), ('coronavirus', 39), ('complications', 38), ('embolism', 37), ('pulmonary embolism', 36), ('clinical', 33), ('remains', 33), ('. however', 33), ('venous thromboembolism', 33), ('thromboembolic', 32), ('needed', 31), ('events', 31), ('infection', 31), ('case', 30), ('high', 29), ('therapy', 29), ('severe', 29), ('. studies', 28), ('hospitalized', 27), ('may', 27), ('treatment', 26), ('bleeding', 26), ('optimal', 26), ('incidence', 26), ('patients .', 26), ('coronavirus disease', 26), ('thromboprophylaxis', 25), ('known', 25), ('therapeutic', 24), ('increased', 24)]
topic-2
[('covid19', 220), ('pregnancy', 133), ('sarscov2', 128), ('women', 126), ('pregnant', 113), ('infection', 102), ('unknown', 82), ('pregnant women', 78), ('studies', 68), ('disease', 65), ('risk', 62), ('coronavirus', 61), ('severe', 49), ('outcomes', 48), ('transmission', 47), ('research', 47), ('known', 43), ('neonates', 38), ('maternal', 38), ('clinical', 35), ('sarscov2 infection', 34), ('little', 32), ('associated', 32), ('study', 31), ('2019', 30), ('evidence', 29), ('respiratory', 29), ('coronavirus disease', 29), ('little known', 29), ('may', 28), ('however', 28), ('patients', 28), ('health', 28), ('needed', 27), ('vertical', 27), ('mothers', 27), ('cases', 27), ('whether', 27), ('effects', 27), ('impact', 27), ('disease 2019', 27), ('unknown .', 27), ('coronavirus disease 2019', 27), ('vertical transmission', 26), ('covid19 pregnancy', 26), ('review', 25), ('acute', 25), ('2', 25), ('syndrome', 24), ('data', 24)]
topic-3
[('covid19', 271), ('patients', 163), ('cardiac', 120), ('unknown', 90), ('disease', 84), ('myocarditis', 70), ('infection', 60), ('injury', 57), ('myocardial', 54), ('cardiovascular', 49), ('clinical', 47), ('unknown .', 46), ('however', 45), ('studies', 43), ('acute', 41), ('heart', 41), ('covid19 patients', 39), ('coronavirus', 35), ('outcomes', 33), ('. however', 32), ('research', 31), ('associated', 31), ('covid19 infection', 31), ('may', 30), ('severe', 30), ('known', 30), ('needed', 29), ('mortality', 29), ('2019', 28), ('reported', 27), ('pandemic', 27), ('myocardial injury', 26), ('coronavirus disease', 26), ('cases', 25), ('sarscov2', 25), ('failure', 25), ('incidence', 25), ('disease 2019', 25), ('involvement', 24), ('study', 24), ('coronavirus disease 2019', 24), ('longterm', 23), ('hospitalized', 23), ('patients covid19', 23), ('2019 covid19', 23), ('disease 2019 covid19', 23), ('patient', 22), ('mechanisms', 22), ('still', 21), ('complications', 21)]
topic-4
[('sarscov2', 221), ('coronavirus', 219), ('respiratory', 201), ('severe', 183), ('acute', 182), ('syndrome', 172), ('acute respiratory', 169), ('severe acute', 157), ('respiratory syndrome', 157), ('severe acute respiratory', 157), ('covid19', 154), ('acute respiratory syndrome', 151), ('2', 138), ('syndrome coronavirus', 132), ('respiratory syndrome coronavirus', 132), ('coronavirus 2', 128), ('syndrome coronavirus 2', 125), ('2 sarscov2', 118), ('coronavirus 2 sarscov2', 114), ('disease', 102), ('unknown', 101), ('infection', 80), ('patients', 75), ('coronavirus disease', 56), ('2019', 54), ('known', 47), ('pandemic', 47), ('disease 2019', 47), ('2019 covid19', 45), ('coronavirus disease 2019', 45), ('sarscov2 infection', 44), ('disease 2019 covid19', 44), ('however', 36), ('viral', 34), ('immune', 34), ('clinical', 34), ('virus', 32), ('little', 31), ('unknown .', 31), ('little known', 30), ('caused', 29), ('studies', 27), ('study', 25), ('remains', 25), ('infections', 23), ('. however', 23), ('risk', 22), ('whether', 21), ('2 sarscov2 infection', 20), ('still', 19)]
topic-5
[('covid19', 124), ('health', 123), ('nurses', 123), ('pandemic', 102), ('mental', 63), ('covid19 pandemic', 54), ('workers', 53), ('mental health', 52), ('care', 51), ('research', 50), ('study', 50), ('work', 44), ('unknown', 41), ('psychological', 40), ('healthcare', 37), ('impact', 37), ('stress', 37), ('among', 37), ('known', 36), ('little', 34), ('frontline', 34), ('future', 33), ('support', 31), ('nursing', 31), ('patients', 31), ('little known', 31), ('working', 28), ('studies', 27), ('pandemic .', 27), ('however', 25), ('factors', 25), ('wellbeing', 23), ('experiences', 21), ('. study', 21), ('needed', 19), ('hospital', 19), ('outbreak', 19), ('future research', 19), ('. however', 19), ('health care', 19), ('findings', 18), ('effects', 18), ('experienced', 18), ('healthcare workers', 17), ('hcws', 16), ('strategies', 16), ('symptoms', 16), ('disease', 15), ('levels', 15), ('anxiety', 15)]
topic-6
[('patients', 132), ('covid19', 112), ('respiratory', 70), ('ventilation', 53), ('studies', 50), ('unknown', 41), ('prone', 33), ('acute', 33), ('mechanical', 31), ('outcomes', 31), ('failure', 31), ('oxygen', 30), ('respiratory failure', 30), ('may', 26), ('mechanical ventilation', 26), ('ards', 25), ('covid19 patients', 25), ('acute respiratory', 25), ('disease', 23), ('pressure', 22), ('positioning', 22), ('needed', 21), ('prone positioning', 20), ('whether', 19), ('mortality', 19), ('oxygenation', 19), ('future', 18), ('clinical', 18), ('care', 18), ('intubation', 18), ('icu', 18), ('research', 17), ('positive', 17), ('hfnc', 17), ('patients covid19', 17), ('. studies', 17), ('ventilator', 16), ('however', 16), ('treatment', 16), ('unknown .', 16), ('support', 15), ('data', 14), ('study', 14), ('noninvasive', 14), ('use', 14), ('high', 14), ('lung', 14), ('need', 14), ('studies needed', 14), ('pandemic', 13)]
topic-7
[('online', 118), ('learning', 108), ('students', 86), ('research', 85), ('education', 67), ('future', 63), ('teaching', 49), ('study', 44), ('elearning', 38), ('studies', 37), ('pandemic', 33), ('future research', 29), ('covid19', 28), ('medical', 28), ('online learning', 27), ('use', 21), ('virtual', 21), ('student', 21), ('digital', 20), ('teachers', 19), ('technology', 19), ('educational', 18), ('performance', 18), ('implications', 16), ('. future', 16), ('unknown', 15), ('supplementary', 15), ('information', 15), ('needed', 15), ('knowledge', 15), ('future studies', 15), ('covid19 pandemic', 15), ('impact', 14), ('need', 14), ('results', 14), ('also', 14), ('environment', 14), ('remote', 14), ('courses', 14), ('perceived', 14), ('. research', 14), ('delivery', 13), ('learners', 13), ('online teaching', 13), ('. study', 13), ('methods', 12), ('support', 12), ('however', 12), ('outcomes', 12), ('satisfaction', 12)]
topic-8
[('coronavirus', 122), ('unknown', 108), ('covid19', 103), ('china', 98), ('2019', 93), ('disease', 89), ('pneumonia', 86), ('wuhan', 81), ('respiratory', 67), ('december', 65), ('sarscov2', 56), ('december 2019', 52), ('pneumonia unknown', 49), ('severe', 48), ('acute', 47), ('acute respiratory', 43), ('syndrome', 42), ('wuhan china', 41), ('severe acute', 39), ('respiratory syndrome', 39), ('severe acute respiratory', 39), ('outbreak', 38), ('health', 36), ('cases', 36), ('virus', 35), ('novel', 35), ('acute respiratory syndrome', 35), ('cause', 34), ('coronavirus disease', 32), ('caused', 29), ('new', 29), ('world', 28), ('novel coronavirus', 28), ('hubei', 27), ('2', 27), ('reported', 27), ('2019 covid19', 27), ('pandemic', 26), ('first', 26), ('unknown cause', 25), ('patients', 24), ('disease 2019', 24), ('disease 2019 covid19', 24), ('identified', 23), ('etiology', 23), ('syndrome coronavirus', 23), ('coronavirus 2', 23), ('china december', 23), ('respiratory syndrome coronavirus', 23), ('infection', 22)]
topic-9
[('ace2', 151), ('covid19', 94), ('sarscov2', 88), ('unknown', 49), ('expression', 46), ('studies', 45), ('receptor', 44), ('enzyme', 43), ('2', 42), ('patients', 41), ('infection', 41), ('disease', 39), ('angiotensinconverting', 37), ('angiotensinconverting enzyme', 34), ('however', 31), ('entry', 28), ('enzyme 2', 28), ('unknown .', 27), ('protein', 26), ('system', 25), ('angiotensinconverting enzyme 2', 25), ('human', 23), ('host', 23), ('may', 23), ('2 ace2', 23), ('enzyme 2 ace2', 23), ('. however', 22), ('cells', 20), ('sarscov2 infection', 20), ('virus', 19), ('tmprss2', 19), ('remains', 18), ('viral', 18), ('clinical', 18), ('cell', 18), ('lung', 18), ('covid19 .', 18), ('receptors', 17), ('effect', 17), ('severity', 17), ('research', 17), ('inhibitors', 16), ('drugs', 16), ('coronavirus', 16), ('angiotensin', 16), ('cellular', 16), ('needed', 16), ('use', 16), ('arbs', 15), ('although', 15)]
topic-10
[('covid19', 151), ('disease', 123), ('coronavirus', 109), ('2019', 87), ('coronavirus disease', 84), ('unknown', 72), ('disease 2019', 71), ('coronavirus disease 2019', 70), ('2019 covid19', 68), ('disease 2019 covid19', 68), ('patients', 49), ('clinical', 30), ('pandemic', 26), ('known', 25), ('little', 21), ('little known', 21), ('still', 18), ('cases', 17), ('unknown .', 17), ('novel', 16), ('risk', 15), ('infection', 15), ('guidelines', 14), ('health', 13), ('symptoms', 13), ('virus', 13), ('factors', 13), ('research', 13), ('covid19 pandemic', 13), ('disease covid19', 13), ('severe', 11), ('study', 11), ('countries', 11), ('world', 10), ('china', 10), ('characteristics', 10), ('caused', 10), ('spread', 10), ('remains', 10), ('osh', 10), ('osh guidelines', 10), ('2019 covid19 pandemic', 10), ('coronavirus disease covid19', 10), ('outbreak', 9), ('worldwide', 9), ('2020', 9), ('many', 9), ('treatment', 9), ('novel coronavirus', 9), ('infectious', 8)]
topic-11
[('covid19', 141), ('patients', 93), ('pandemic', 75), ('surgery', 64), ('unknown', 56), ('surgical', 49), ('covid19 pandemic', 47), ('elective', 43), ('impact', 38), ('risk', 32), ('care', 30), ('procedures', 26), ('disease', 23), ('research', 21), ('infection', 21), ('2019', 20), ('2020', 20), ('unknown .', 20), ('health', 19), ('study', 18), ('coronavirus', 18), ('known', 16), ('future', 16), ('patient', 16), ('uncertain', 15), ('clinical', 14), ('hospital', 14), ('outcomes', 14), ('studies', 13), ('undergoing', 13), ('cases', 13), ('practice', 13), ('surgeries', 13), ('healthcare', 13), ('positive', 13), ('little', 12), ('surgeons', 12), ('effects', 12), ('postoperative', 12), ('mortality', 12), ('complications', 12), ('little known', 12), ('coronavirus disease', 12), ('2019 covid19', 12), ('covid19 infection', 12), ('management', 11), ('safety', 11), ('may', 11), ('lockdown', 11), ('hip', 11)]
topic-12
[('model', 116), ('unknown', 77), ('data', 69), ('covid19', 63), ('parameters', 52), ('models', 48), ('epidemic', 41), ('number', 34), ('disease', 33), ('transmission', 31), ('using', 31), ('unknown parameters', 28), ('pandemic', 26), ('control', 26), ('dynamics', 26), ('method', 25), ('time', 25), ('results', 24), ('infected', 24), ('cases', 23), ('epidemiological', 23), ('estimate', 22), ('uncertain', 22), ('proposed', 21), ('research', 20), ('new', 20), ('study', 20), ('rate', 20), ('future', 19), ('infection', 19), ('spread', 18), ('based', 18), ('prediction', 17), ('social', 17), ('analysis', 17), ('paper', 16), ('outbreak', 15), ('different', 15), ('used', 15), ('covid19 pandemic', 15), ('measures', 14), ('estimated', 14), ('individuals', 14), ('also', 13), ('infectious', 13), ('infections', 13), ('distribution', 13), ('factors', 13), ('modeling', 12), ('estimation', 12)]
topic-13
[('vaccine', 144), ('covid19', 127), ('vaccination', 81), ('covid19 vaccine', 47), ('vaccines', 37), ('health', 35), ('among', 30), ('uncertain', 29), ('acceptance', 29), ('covid19 vaccination', 29), ('future', 27), ('hesitancy', 25), ('uptake', 24), ('studies', 22), ('information', 22), ('study', 22), ('research', 21), ('known', 21), ('public', 19), ('unknown', 19), ('safety', 19), ('little', 19), ('vaccine hesitancy', 19), ('little known', 19), ('willingness', 18), ('attitudes', 17), ('trust', 17), ('associated', 17), ('factors', 17), ('may', 16), ('population', 15), ('risk', 15), ('vaccinated', 15), ('likely', 14), ('covid19 vaccines', 14), ('intention', 13), ('participants', 13), ('effects', 13), ('efficacy', 12), ('influenza', 12), ('results', 12), ('needed', 12), ('however', 12), ('knowledge', 12), ('. future', 12), ('receive', 11), ('patients', 11), ('campaigns', 11), ('low', 11), ('healthcare', 11)]
topic-14
[('unknown', 93), ('pneumonia', 84), ('december', 82), ('2019', 82), ('wuhan', 80), ('china', 73), ('december 2019', 66), ('pneumonia unknown', 50), ('cases', 38), ('hubei', 35), ('reported', 34), ('province', 33), ('hubei province', 29), ('health', 28), ('cause', 28), ('wuhan china', 27), ('unknown cause', 26), ('etiology', 25), ('city', 25), ('unknown etiology', 24), ('china december', 24), ('patients', 22), ('province china', 22), ('hubei province china', 22), ('cases pneumonia', 21), ('cases pneumonia unknown', 21), ('outbreak', 20), ('cluster', 19), ('origin', 18), ('wuhan hubei', 18), ('china december 2019', 18), ('pneumonia unknown cause', 18), ('31', 17), ('unknown origin', 17), ('pneumonia unknown etiology', 17), ('world', 16), ('wuhan hubei province', 16), ('reported wuhan', 15), ('pneumonia cases', 14), ('organization', 13), ('world health', 13), ('health organization', 13), ('wuhan city', 13), ('world health organization', 13), ('chinese', 11), ('detected', 11), ('december 31', 11), ('31 2019', 11), ('december 31 2019', 11), ('first', 10)]
topic-15
[('health', 112), ('covid19', 111), ('mental', 108), ('mental health', 92), ('pandemic', 70), ('covid19 pandemic', 45), ('impact', 36), ('research', 34), ('studies', 25), ('patients', 24), ('people', 20), ('known', 19), ('unknown', 19), ('effects', 19), ('psychological', 17), ('associated', 17), ('study', 17), ('little', 17), ('psychiatric', 16), ('among', 16), ('population', 16), ('little known', 16), ('needed', 15), ('public', 15), ('future', 14), ('impact covid19', 14), ('need', 13), ('treatment', 13), ('pandemic .', 13), ('schizophrenia', 12), ('risk', 12), ('disorders', 12), ('however', 12), ('may', 11), ('clinical', 11), ('infection', 11), ('general', 11), ('. research', 11), ('outbreak', 10), ('consequences', 10), ('vulnerable', 10), ('care', 10), ('factors', 9), ('coronavirus', 9), ('disease', 9), ('sarscov2', 9), ('covid19 pandemic .', 9), ('mechanisms', 8), ('especially', 8), ('adults', 8)]
topic-16
[('covid19', 145), ('patients', 53), ('studies', 42), ('unknown', 26), ('risk', 24), ('research', 22), ('clinical', 20), ('disease', 19), ('covid19 patients', 19), ('future', 18), ('infection', 16), ('children', 15), ('associated', 15), ('needed', 14), ('covid19 .', 14), ('may', 11), ('factors', 11), ('however', 11), ('treatment', 11), ('whether', 11), ('future studies', 11), ('. studies', 11), ('symptoms', 10), ('data', 10), ('known', 10), ('evidence', 10), ('patients .', 10), ('impact', 9), ('outcomes', 9), ('pandemic', 9), ('study', 9), ('risk factors', 9), ('. however', 9), ('among', 8), ('severe', 8), ('results', 8), ('required', 8), ('effects', 8), ('covid19 pandemic', 8), ('provide', 7), ('still', 7), ('increased', 7), ('tests', 7), ('cancer', 7), ('studies .', 7), ('covid19 infection', 7), ('studies needed', 7), ('specific', 6), ('adverse', 6), ('due', 6)]
topic-17
[('covid19', 108), ('transplant', 98), ('recipients', 73), ('patients', 60), ('disease', 52), ('transplant recipients', 48), ('unknown', 46), ('risk', 40), ('sarscov2', 40), ('kidney', 40), ('coronavirus', 34), ('infection', 30), ('transplantation', 29), ('impact', 27), ('severe', 27), ('kidney transplant', 27), ('outcomes', 26), ('organ', 25), ('coronavirus disease', 22), ('pandemic', 21), ('2019', 19), ('immunosuppression', 19), ('solid', 19), ('disease 2019', 19), ('unknown .', 19), ('solid organ', 19), ('coronavirus disease 2019', 19), ('known', 18), ('liver', 18), ('studies', 18), ('mortality', 17), ('population', 17), ('2019 covid19', 17), ('organ transplant', 17), ('disease 2019 covid19', 17), ('kidney transplant recipients', 17), ('acute', 16), ('respiratory', 16), ('remains', 15), ('solid organ transplant', 15), ('may', 13), ('management', 13), ('little', 13), ('little known', 13), ('data', 12), ('however', 12), ('syndrome', 12), ('acute respiratory', 12), ('transplant patients', 12), ('donor', 11)]
topic-18
[('covid19', 135), ('patients', 74), ('risk', 37), ('studies', 34), ('clinical', 29), ('mortality', 27), ('research', 26), ('covid19 patients', 26), ('unknown', 23), ('care', 22), ('symptoms', 20), ('needed', 19), ('factors', 19), ('death', 18), ('severe', 17), ('study', 17), ('health', 17), ('known', 16), ('however', 16), ('may', 16), ('outcomes', 16), ('admission', 15), ('. research', 15), ('using', 14), ('months', 13), ('longterm', 13), ('hospital', 13), ('management', 13), ('future', 13), ('risk factors', 13), ('little', 12), ('symptom', 12), ('little known', 12), ('research needed', 12), ('model', 11), ('potential', 10), ('high', 10), ('disease', 10), ('2020', 10), ('covid19 .', 10), ('associated', 9), ('patient', 9), ('among', 9), ('models', 9), ('setting', 9), ('. research needed', 9), ('whether', 8), ('infection', 8), ('long', 8), ('reported', 8)]
topic-19
[('social', 118), ('media', 117), ('social media', 95), ('covid19', 70), ('health', 60), ('public', 51), ('information', 48), ('study', 46), ('research', 39), ('pandemic', 39), ('use', 32), ('future', 31), ('studies', 30), ('communication', 26), ('however', 25), ('platforms', 25), ('covid19 pandemic', 25), ('knowledge', 22), ('online', 21), ('little', 20), ('known', 20), ('little known', 20), ('. however', 20), ('impact', 19), ('public health', 18), ('misinformation', 17), ('analysis', 17), ('. study', 17), ('users', 16), ('media use', 16), ('future research', 16), ('content', 15), ('role', 14), ('media platforms', 14), ('social media platforms', 14), ('risk', 13), ('among', 13), ('data', 12), ('also', 12), ('unknown', 12), ('needed', 12), ('used', 12), ('vaccines', 12), ('sentiment', 12), ('future studies', 12), ('vaccination', 11), ('important', 11), ('awareness', 11), ('spread', 11), ('twitter', 11)]
topic-20

In [ ]:
with open('Topics Keywords with frequencies.txt', 'w') as f:
    f.write(dst)

# After Manually Labelled

In [ ]:
import pandas as pd
df = pd.read_csv("articles_with_topics.csv")
df.head(3)

,cord_uid,title,doi,abstract,publish_time,authors,journal,doi.1,pmcid,pubmed_id,publish_time_new,lang,sentences,words,topics,new_topics
0,azdtbnqj,Combined Hyperglycemic Hyperosmolar Syndrome a...,10.1155/2021/6429710,although most children with coronavirus diseas...,2021-11-27,"Tseng, Yu Shan; Tilford, Bradley; Sethuraman, ...",Case Rep Crit Care,10.1155/2021/6429710,PMC8627355,34791286.0,2021-11-27,en,"as the pandemic continues, clinicians should ...",further studies,116,-1
1,k8nbgxsf,Evidences suggesting a possible role of Vitami...,10.4103/ijp.ijp_654_20,the severe acute respiratory syndrome coronavi...,2021-11-24,"Singh, Shruti; Singh, C. M.; Ranjan, Alok; Kum...",Indian J Pharmacol,10.4103/ijp.ijp_654_20,PMC8641745,34854410.0,2021-11-24,en,while some risk factors such as the presence ...,further research,-1,-1
2,t3tlj38t,Predictors to Use Mobile Apps for Monitoring C...,10.2196/28416,ehealth apps have been recognized as a valuab...,2021-12-20,"Jansen-Kosterink, Stephanie; Hurmuz, Marian; d...",JMIR Form Res,10.2196/28416,PMC8691407,34818210.0,2021-12-20,en,ehealth apps have been recognized as a valuab...,unknown,-1,-1

In [ ]:
len(df)

12853

In [ ]:
tp = {
    -1:"Unlabelled",
    0:"Unlabelled",
    1:"TeleHealth",
    2: "Thrombosis",
    3:"Maternal & Neonatal (Pregnancy)",
    4:"Cardiovascular Complications",
    5: "Neurological Complications",
    6: "Surgical Considerations",
    7:"Respiratory (Pulmonary) Complications",
    8 :"Prediction Models",
    9: "Vaccination Efficacy & Safety",
    10:"Mental Health",
    11:"Education",
    12:"Healthcare workers’ Mental Health",
    13:"Vaccination Hesitancy",
    14:"Vaccination Hesitancy",
    15:"Respiratory (Pulmonary) Complications",
    16:"Origin of COVID-19",
    17:"Angiotensin Converting Enzyme (ACE)",
    18:"Media & Communication",
    19:"Origin of COVID-19",
    20:"Diabetes",
    21:"Origin of COVID-19",
    22:"General",
    23:"Organ Transplantation",
    24:"Treatment of COVID-19",
    25:"Mortality",
    26: "Dietary Supplementation",
    27:"General",
    28:"General",
    29: "Obesity",
    30:"Maternal & Neonatal (Pregnancy)",
    31: "Pediatrics",
    32: "Transmission",
    33: "Hepatic Complications",
    34: "Herbal Medicine",
    35: "Public Policies & Precaution Measures",
    36: "Ethnicity",
    37: "Cancer",
    38:"General",
    39: "Food Security",
    40: "Wastewater Surveillance",
    41:"Vaccination Hesitancy",
    42:"General",
    43: "Dental & Oral Health",
    44: "Face Mask",
    45:"TeleHealth",
    46: "Olfactory (Smell & Taste)",
    47: "Emerging Variants",
    48: "Support System",
    49: "Immune System"
}

In [ ]:
df["Topic Labels"]=df["new_topics"].apply(lambda x: tp[x])

In [ ]:
df.groupby(by=["Topic Labels"])["title"].count()

Topic Labels
Angiotensin Converting Enzyme (ACE)       113
Cancer                                     64
Cardiovascular Complications              216
Dental & Oral Health                       59
Diabetes                                   95
Dietary Supplementation                    80
Education                                 136
Emerging Variants                          56
Ethnicity                                  65
Face Mask                                  58
Food Security                              62
General                                   370
Healthcare workers’ Mental Health         136
Hepatic Complications                      70
Herbal Medicine                            66
Immune System                              52
Maternal & Neonatal (Pregnancy)           294
Media & Communication                     109
Mental Health                             138
Mortality                                  87
Neurological Complications                177
Obesity                                    77
Olfactory (Smell & Taste)                  56
Organ Transplantation                      92
Origin of COVID-19                        318
Pediatrics                                 76
Prediction Models                         146
Public Policies & Precaution Measures      66
Respiratory (Pulmonary) Complications     268
Support System                             55
Surgical Considerations                   158
TeleHealth                                305
Thrombosis                                224
Transmission                               75
Treatment of COVID-19                      90
Unlabelled                               7837
Vaccination Efficacy & Safety             144
Vaccination Hesitancy                     303
Wastewater Surveillance                    60
Name: title, dtype: int64